refactor: Page layout and include repository data
ls1intum/Helios pull request #137
Opened 2024-12-28 21:49 UTC by thielpa

2025-01-02 21:20 UTC, TurkerKoc commented on client/src/app/pages/project-settings/project-settings.component.html
> +      } @else {
With this change, there should be no groups in order to see this 'No groups available' dialog with + button to add a new group. Once we add a group, we are no longer able to add more groups. We should put Add Group button back

2025-01-02 21:21 UTC, TurkerKoc commented on client/src/app/pages/project-settings/project-settings.component.html
> +      <!-- TODO: Remove and replace by update handlers directly on dropdowns -->
We can put Add Group button back here

2025-01-02 21:23 UTC, TurkerKoc requested changes
Thanks for the great job! New layout with headers matching looks really nice! There is one minor issue in Project Settings and some conflicts with the new project settings page as well. It's good to go we update project settings! 🚀

2025-01-03 15:09 UTC, thielpa commented on client/src/app/pages/project-settings/project-settings.component.html
> +      <!-- TODO: Remove and replace by update handlers directly on dropdowns -->
I put the button here, i think this is more intuitive for the user. Otherwise he/she has to search on the page. Hope this is fine, otherwise I can change it again.
![image](https://github.com/user-attachments/assets/7a819d82-75e8-475c-92c5-c65c15a8aad0)

2025-01-04 18:36 UTC, TurkerKoc approved these changes

2025-01-04 18:44 UTC, merged